version: "3.8"
services:
  mysql-local:
    container_name: mysql-local
    image: mysql:latest
    ports:
      - "3306:3306"
    environment:
      - MYSQL_DATABASE=EmploymentSupport
      - MYSQL_ROOT_PASSWORD=password
      - MYSQL_USER=dbuser
      - MYSQL_PASSWORD=password
    volumes:
      - my-db:/var/lib/mysql
      - ./database-setup:/docker-entrypoint-initdb.d
    networks:
      - spring-cloud-network
    healthcheck:
      test: [ "CMD", "mysqladmin" ,"ping", "-h", "localhost" ]
      interval: 10s
      retries: 10
      start_period: 10s
      timeout: 3s

  backend:
    container_name: backend
    image: backend:latest
    build:
      context: ../backend
      dockerfile: ../backend/Dockerfile
    depends_on:
      mysql-local:
        condition: service_healthy
    environment:
      DB_HOST: mysql-local
      DB_NAME: EmploymentSupport
      DB_USER: "dbuser"
      DB_PASSWORD: "password"
    ports:
      - "8080:8080"
    networks:
      - spring-cloud-network
      - spring-react

  frontend:
    container_name: frontend
    image: frontend:latest
    build:
      context: ../frontend
      dockerfile: ../frontend/Dockerfile
    ports:
      - "3000:3000"
    stdin_open: true
    environment:
      - CHOKIDAR_USEPOLLING=true
    depends_on:
      - backend
    networks:
      - spring-react
    command: npm start

volumes:
  my-db:

networks:
  spring-cloud-network:
    driver: bridge
  spring-react:
    driver: bridge
